export default [
    {
        label:'基本说明',
        component:'baseDesc'
    },
    {
        label:'基础图表',
        component:'baseChart'
    },
    {
        label:'legend-外部设置点击事件',
        component:'legendClickDiy'
    },
    {
        label:'tooltip-自定义样式',
        component:'diyTooltip'
    },
    {
        label:'tooltip-默认显示并轮播显示',
        component:'defaultShowTooltip'
    },
    {
        label:'折线图-连接断开空数据',
        component:'connectNulls'
    },
    {
        label:'折线图-部分虚线',
        component:'linePartDashed'
    },
]